# .github/dependabot.yml
version: 2
updates:    # Maintain dependencies for Composer
    - package-ecosystem: "bundler"
      directory: "/"
      versioning-strategy: increase
      schedule:
          interval: "weekly"
