# Text for `site.*`
title: Jekyll theme for one-page README.md
logo_url: https://avatars.githubusercontent.com/u/117988194?s=200&v=4
url: https://achvm.github.io/achvm-theme
baseurl: ""

permalinks: pretty

include:
  - LICENSE

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-titles-from-headings

# Exclude the `vendor` folder created by build process
exclude:
  - vendor

defaults:
  -
    scope:
      path: "index.md"
    values:
      order: 0 # Show the index at the top of the navigation
  -
    scope:
      path: "LICENSE.md"
    values:
      order: 100 # Show the license at the bottom of the navigation

titles_from_headings:
  strip_title: true

syntax_highlighter: rouge
